[package]
name = "mynah"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.103"
calloop = "0.14"
calloop-wayland-source = "0.4"
cpal = "0.18.1"
env_logger = "0.11.11"
evdev = "0.13.2"
ksni = { version = "0.3.6", default-features = false, features = ["async-io", "blocking"] }
log = "0.4.33"
smithay-client-toolkit = "0.20.0"
tiny-skia = "0.12.0"
transcribe-cpp = { version = "0.1.3", features = ["vulkan"] }
wayland-client = "0.31.14"

